//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clothes_UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cl
    {
        public int clID { get; set; }
        public string clName { get; set; }
        public int clnum { get; set; }
        public int clprice { get; set; }
        public string clgys { get; set; }
    }
}
