//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clothes_UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orders()
        {
            this.in_money = new HashSet<in_money>();
            this.order_details = new HashSet<order_details>();
            this.out_repertory = new HashSet<out_repertory>();
        }
    
        public int order_id { get; set; }
        public int customer_id { get; set; }
        public System.DateTime order_starttime { get; set; }
        public System.DateTime order_endtime { get; set; }
        public string person_handling { get; set; }
        public string operator_per { get; set; }
        public decimal order_paid { get; set; }
        public decimal order_unpaid { get; set; }
        public string order_status { get; set; }
        public string ss { get; set; }
    
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<in_money> in_money { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_details> order_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<out_repertory> out_repertory { get; set; }
    }
}
