//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clothes_UI.Models
{
    using System;
    
    public partial class Quality_test_index_selecte_Result1
    {
        public System.DateTime product_time { get; set; }
        public string operator_per { get; set; }
        public int pro_production_id { get; set; }
        public string status { get; set; }
        public string product_name { get; set; }
        public string product_type { get; set; }
        public int product_plan_id { get; set; }
        public int product_details_num { get; set; }
        public int product_plan_details_id { get; set; }
    }
}
