//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clothes_UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Product_index_selecte
    {
        public int product_id { get; set; }
        public string product_num { get; set; }
        public string product_name { get; set; }
        public string product_producer { get; set; }
        public string product_type { get; set; }
        public string product_price { get; set; }
        public string product_address { get; set; }
        public string unit { get; set; }
        public string size { get; set; }
        public int pro_repertory_num { get; set; }
        public int repertory_id { get; set; }
    }
}
